config/routes.rb
Rails.application.routes.draw do

root 'home#index'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'

  post '/signup', to: 'users#create'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users

  resources :people do
  	resources :hobbies
  	resources :locations
  end
end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
	belongs_to :person
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
	belongs_to :user
	has_one :hobby, dependent: :destroy
	has_one :location, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
	validates_uniqueness_of :email
	validates_presence_of :email, :password_digest
	has_secure_password 
	has_one :person
	after_create :create_person

	def create_account
		Person.create(user_id: self.id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :person
  before_action :hobby, only: [:show, :edit, :update, :destroy]

  def index
  	@hobby = @person.hobby
  end

  def show
  end
  
  def new
    @hobby = Hobby.new
  end
  
  def create
	  @hobby = @person.create_hobby(hobby_params)
	  if @hobby.save
	    # flash[:success] = "hobby with name #{@hobby.name} created!"
	    redirect_to person_hobby_path(@person, @hobby)
	  else
	    render :new
	  end
  end

  def update
    if @hobby.update(hobby_params)
      # flash[:success] = "hobby with name: #{@hobby.name} updated!"
      redirect_to person_hobby_path(@person, @hobby)
    else
      render :edit
    end
  end

  def edit
  end

 

  def destroy  
  	# hobby_name = @hobby.name
  	@hobby.destroy
  	redirect_to person_path(@person)
  end

  private
  	def hobby_params
  			params.require(:hobby).permit(:music, :tv, :activities)
  	end

   


    def hobby
      @hobby = Hobby.find_by_id(params[:id])
    end

    def person
      @person = Person.find(params[:person_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  
  before_action :person
  before_action :location, only: [:show, :edit, :update, :destroy]

  def index
    @location = @person.location
  end

  def show
  end

  def new
    @location = Location.new 
  end

  def create
    @location = @person.create_location(location_params)
    if @location.save
      redirect_to person_location_path(@person, @location)
    else
      render :new
    end
  end
  
  def update
   
    if @location.update(location_params)
      redirect_to person_location_path(@person, @location)
    else
      render :edit
    end
  end

  def edit
  end
  
  def destroy
    @location.destroy
    redirect_to person_path(@person)
  end



private

  def location_params
    params.require(:location).permit(:city, :state)
  end
  
  def location
    @location = Location.find_by_id(params[:id])
  end
  
  def person
    @person = Person.find(params[:person_id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :person, only:[:edit, :destroy, :update]
  # $pur_profiles = []

  def index
    @people = Person.all
    if params[:search]
      @people = Person.search(params[:search]).order("created_at DESC")
    else
      @people = Person.all.order('created_at DESC')
    end
  end

  def new
  	@person = Person.new
  end

  def edit
  end

  def create
  	@person = current_user.create_person(person_params)
    if @person.save
      # session[:person_id] = @person.id
      # redirect_to accounts_show_path
      # $pur_profiles << @person
      # flash[:success] = "#{person.name}, you have taken your first step toward love!"
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def show
    @person = current_user.person
  end
  

  def destroy
  	# person = @person
    @person.destroy
    # flash[:success] = "Your profile has now been deleted #{person.name}"
    redirect_to people_path
  end

  def update
  	 if @person.update(person_params)
      # flash[:success] = "Your profile has now been updated!"
      redirect_to person_path(@person)
    else
      render :edit
    end
 	end
	private
		def person_params
			params.require(:person).permit(:name, :age, :user_id)
		end

		def person
			@person = Person.find(params[:id])
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to person_path(user.person)
		else
			redirect_to '/login'
		end
	end

	def destroy
    session[:user_id] = nil
    redirect_to '/'
	end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      session[:user_id] = @user.id
  		redirect_to new_person_path(user_id: @user.id)
  	else
      render :new
    end
  end

  private 

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hobbies/_form.html.erb
<%= form_for [@person, @hobby] do |f| %>
  <%= f.label :music %>
  <%= f.text_field :music %>

  <%= f.label :tv %>
  <%= f.text_field :tv %>

  <%= f.label :activities %>
  <%= f.text_field :activities %>
  
  <%= f.submit %>
<% end %>

app/views/hobbies/edit.html.erb
<h1>Edit your profile: </h1>
<hr/>

<%= render(partial: 'form') %>

app/views/hobbies/index.html.erb
<h1>Your Hobbies</h1>
<p>
<% if @hobby %>

  Music: <%= @hobby.music %><br />
  TV: <%= @hobby.tv %><br />
  Activites: <%= @hobby.activities %>
<% else %>
  <h3>No hobbies, please add one!</h3>
<% end %>
</p>

<hr />


<%= link_to 'Edit Hobbies', edit_person_hobby_path(@person, @hobby) %>
<%= link_to 'New Hobbies', new_person_hobby_path(@person) %>
<%= link_to 'Back', person_path(@person) %>

app/views/hobbies/new.html.erb
<%= render(partial: 'form') %>

app/views/hobbies/show.html.erb
<h1> Your List of Purrfect Hobbies, <%= @person.name %> </h1>
<hr/>
<h1>Music: <%= @hobby.music %></h1>
<h1>TV: <%= @hobby.tv %></h1>
<h1>Activities: <%= @hobby.activities %></h1>
<hr />

<%= link_to 'Back', person_path(@person) %>
<%= link_to 'Edit', edit_person_hobby_path(@person, @hobby) %>

<%= link_to 'Delete', person_hobby_path(@person, @hobby), method: :delete, data: {confirm: 'Really delete?'} %>

<%= link_to 'Personal Locations', new_person_location_path(@person) %>

<%= link_to 'All Profiles', people_path %>

app/views/home/index.html.erb
<h2>Welcome to Purrr</h2>
<%= link_to 'Sign Up', signup_path %>
<%= link_to 'Login', login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for [@person, @location] do |f| %>
  
  <%= f.label :city %>
  <%= f.text_field :city %>
  
  <%= f.label :state %>
  <%= f.text_field :state %>
  
  <%= f.submit %>

<% end %>

app/views/locations/create.html.erb
<h1>Locations#create</h1>
<p>Find me in app/views/locations/create.html.erb</p>

app/views/locations/edit.html.erb
<h1>Edit your location: </h1>
<hr/>

<%= render(partial: 'form') %>

app/views/locations/index.html.erb
<h1>Your Location,<%= @person.name %>:</h1>

<hr />

<% if @location %>
  
        <%= @location.city %>
        <%= @location.state %>
<% else %>
  <h3>No location, please add one!</h3>
<% end %>

<hr />


<%= link_to 'New Location', new_person_location_path(@person) %>

<%= link_to 'Back', person_path(@person) %>

app/views/locations/new.html.erb
<h1>Purrrfect your profile, <%= @person.name %>:</h1>

<p>Please enter your general location to better serve your matching needs!</p>

<%= render(partial: 'form') %>

app/views/locations/show.html.erb
<h1> Your Location: </h1>
<hr/>
<h1>City: <%= @location.city %></h1>
<h1>State: <%= @location.state %></h1>
<hr />

<%= link_to 'Edit', edit_person_location_path(@person, @location) %>

<%= link_to 'Delete', person_location_path(@person, @location), method: :delete, data: {confirm: 'Really delete?'} %>

<%= link_to 'Back', person_path(@person) %>

<%= link_to 'All Profiles', people_path %>

app/views/locations/update.html.erb
<h1>Locations#update</h1>
<p>Find me in app/views/locations/update.html.erb</p>

app/views/people/_form.html.erb
<div class="form_div">
<%= form_for @person do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>
  <p class="waves-effect waves-light btn red">
  <%= f.submit %>
  </p>
  <% end %>
</div>

app/views/people/edit.html.erb
<h1>Make your profile more Purrfect: <%= @person.name %></h1>
<hr />

<%= render(partial: 'form') %>

app/views/people/index.html.erb
<h1>Welcome to Pur</h1>
<h2>The online dating app to help you find your purrfect match</h2>

<% if @people.any? %>
  <ul>
    <% @people.each do |person| %>
      <li>
        <%= link_to "#{person.name}", person_path(person) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <h3>You have not created your profile yet, please create one!</h3>
<% end %>

<hr />

app/views/people/new.html.erb
<h1>New Profile</h1>
<br/>

<%= render(partial: 'form') %>

app/views/people/show.html.erb
<h1>
	Welcome <%= @person.name %>!
</h1> 
<% if !(@person.hobby && @person.location) %>

	<h2>
		Congratulations on taking your first step towards your Purrrrfect match...
	</h2>

	<h2>
	  We know you are <%= @person.age%> years old. But, please tell us more by finishing your profile here!
	</h2>
<% end %>

<% if @person.hobby %>
	<%= link_to 'Personal Hobbies', person_hobby_path(@person, @person.hobby) %>
  <br/>
<% else %>
	<%= link_to 'Add Hobbies', new_person_hobby_path(@person) %>
	<br/>
<% end %>

<% if @person.location %>
  <%= link_to 'Personal Location', person_location_path(@person, @person.location) %>
  <br/>
<% else %>
  <%= link_to 'Add Location', new_person_location_path(@person) %>
	<br/>
<% end %>

<%= link_to 'EDIT', edit_person_path(@person) %>
<br/>

<%= link_to 'DELETE', person_path(@person), method: :delete, data: {confirm: 'Sure you wanna delete?'} %>
<br/>

<%= link_to 'Logout', logout_path, method: :delete, data: {confirm: 'Sure you wanna leave?'} %>

app/views/users/new.html.erb
<h2>Sign up for Purr</h2>

<%= form_for :user do |f| %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<%= f.submit %>
<% end %>